### PR TITLE
Update test to match Meteor 1.3.5.1

### PR DESCRIPTION
**Pull request by jazeee**
I added some notes to the Readme to assist with testing.

With Meteor 1.3.5.1, I believe invalid subscriptions no longer throw a 404. In order to make the tests pass, I added `@Ignore` to `testInvalidSubscription` function. I believe we can delete that function.

You can verify that Meteor accepts all subscription requests from the client by running the following within Chrome console on a Meteor client. `Meteor.subscribe("InvalidPublicationThatDoesntExist");`. My tests show that this will always work, and return an object with `subscriptionId`, even if there is no publication.

I believe that this is probably better behavior, due to security reasons. (It is probably bad to allow phishers to scan for valid subscriptions such as `Meteor.subscribe("users")`)

### CODE REVIEW

**Comment by kenyee** [comment]
I can't take this PR because of the package renaming.  Some people might be using this already via maven central, so I'd have to rename the package.   Could you please rename the package in the branch you want to merge?
Nice work on the branch BTW.

**Comment by jazeee** [comment]
Oops. I am sorry about that. I should have made this a branch with a small subset of changes.
My master is a significant rewrite of the package, to address my needs, etc.
I will pop out the branch I intended to PR with and submit that.
It is a small fix, comparatively speaking.

**Comment by jazeee** [comment]
Turns out that the changes I intended to incorporate were already in #14 
This is the branch that has the code for this PR:
https://github.com/jazeee/java-ddp-client/tree/update-test-to-match-meteor-1.3.5.1

It has nothing new to merge, since it was all in #14 anyway.

**Comment by jazeee** [comment]
By the way, thanks for the compliment. Your code helped a lot!

**Pull request closed without merging**
