### PR TITLE
Reconnect using an authToken, enable sending message although connection has not been established

### PR DESCRIPTION
**Pull request by tlkiong**
Added a reconnection method based on authToken retrieved from meteor server after authentication successful
	updated the constructor to enable option to enable reconnect or not
	added a pendingMessageQueue to store messages that tried to be sent to the meteor server although the connection has not been established properly
	send all messages in pendingMessageQueue and remove them once connection has been established

### CODE REVIEW

**Comment by tlkiong** [comment]
found a bug.
Will fix it asap

**Comment by kenyee** [comment]
tlkiong: did you get a chance to fix the bug?  Would like to do another release end of this week...thx

**Comment by tlkiong** [comment]
I am working on it.
Will try to do a pull request by Friday

**Comment by kenyee** [comment]
When you're ready, do a pull a request.  I just released 1.0.0.2 w/ the trustmanager ssl reconnect fix you reported.

**Comment by tlkiong** [comment]
@kenyee , I am not sure whether I should do a pull request as my version for this is quite different from yours. Please advice

**Comment by kenyee** [comment]
I'll do a manual merge....can't do an automatic merge because it has diverged too much :-)

**Comment by tlkiong** [comment]
Thanks a lot kenyee. 
Btw, there is a relogin method that I introduced. This is because, at times, I will receive an error message from meteor server that I have been logged out and have to relogin to do anything.
Sending a resume token don't work. Have to relogin using the login credentials provided.
However, I couldn't identify the reason why that happens (it just happens randomly). Plus, this reconnection thing is still a bit buggy.

Do note that there might happen a reconnect-disconnect loop.

This happens when its connected. Then the connection is dc. Then automatically try to reconnect (and successfully connected). Then about 5 seconds later, will dc again. Then automatically try to reconnect (and successfully connected). Then about 5 seconds later, will dc again. This loop will continue forever. There is no stopping condition for this yet.

This happened to me twice. On a random basis. No problem with meteor code nor server issue or internet connection issue.

**Pull request closed without merging**
